#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

while read local_ref local_sha remote_ref remote_sha
do
		# Check for message to update the site commit
        commit=`git log -1 | grep 'PUSH10'`
        if [ -n "$commit" ]
        then
            .git/hooks/cs10sync.sh
            # Not git hooks scripts are run from the project dir.
        fi
done

exit 0
